In [9]:
import pickle   
import os
import pandas as pd

In [10]:
class fill_missing_values_model:
    def __init__(self ,model_missing_folder_path, data_path, column_name):
        self.model_missing_folder_path = model_missing_folder_path
        self.column_name = column_name
        self.data_path = data_path
        
    def read_data(self):
        return pd.read_csv(self.data_path)
        
    def check_same_elements_list(self):
        data = self.read_data()
        series = data[self.column_name].value_counts()
        l=[]
        for i in series:
            l.append(i)
        result = all(element == l[0] for element in l)
        return result
    
#     def load_missing_model(self):
#         os.chdir(self.model_missing_folder_path)
#         model = pickle.load(open(self.column_name + ".pickle", "rb"))
#         return model

In [11]:
fml = fill_missing_values_model(r"C:\Users\Anshdeep\OneDrive\Desktop\Ineuron\Full stack data science course\Python projects\fraudDetection\models_for_missing_values", r"C:\Users\Anshdeep\OneDrive\Desktop\Ineuron\Full stack data science course\Python projects\fraudDetection\Training_Batch_Files\fraudDetection_021119920_010222.csv", "police_report_available")

In [12]:
#fml.load_missing_model()

In [13]:
fml.check_same_elements_list()

False

In [14]:
x = fml.read_data()
x

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,328,48,521585,10/17/2014,OH,250/500,1000,1406.91,0,466132,...,2,YES,71610,6510,13020,52080,Saab,92x,2004,Y
1,228,42,342868,6/27/2006,IN,250/500,2000,1197.22,5000000,468176,...,0,?,5070,780,780,3510,Mercedes,E400,2007,Y
2,134,29,687698,9/6/2000,OH,100/300,2000,1413.14,5000000,430632,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
3,256,41,227811,5/25/1990,IL,250/500,2000,1415.74,6000000,608117,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
4,228,44,367455,6/6/2014,IL,500/1000,1000,1583.91,6000000,610706,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N
5,256,39,104594,10/12/2006,OH,250/500,1000,1351.10,0,478456,...,2,NO,64100,6410,6410,51280,Saab,95,2003,Y
6,137,34,413978,6/4/2000,IN,250/500,1000,1333.35,0,441716,...,0,?,78650,21450,7150,50050,Nissan,Pathfinder,2012,N
7,165,37,429027,2/3/1990,IL,100/300,1000,1137.03,0,603195,...,2,YES,51590,9380,9380,32830,Audi,A5,2015,N
8,27,33,485665,2/5/1997,IL,100/300,500,1442.99,0,601734,...,1,YES,27700,2770,2770,22160,Toyota,Camry,2012,N
9,212,42,636550,7/25/2011,IL,100/300,500,1315.68,0,600983,...,1,?,42300,4700,4700,32900,Saab,92x,1996,N
10,235,42,543610,5/26/2002,OH,100/300,500,1253.12,4000000,462283,...,2,?,87010,7910,15820,63280,Ford,F150,2002,N
11,447,61,214618,5/29/1999,OH,100/300,2000,1137.16,0,615561,...,2,YES,114920,17680,17680,79560,Audi,A3,2006,N
12,60,23,842643,11/20/1997,OH,500/1000,500,1215.36,3000000,432220,...,0,NO,56520,4710,9420,42390,Saab,95,2000,N
13,121,34,626808,10/26/2012,OH,100/300,1000,936.61,0,464652,...,1,NO,7280,1120,1120,5040,Toyota,Highlander,2010,N
14,180,38,644081,12/28/1998,OH,250/500,2000,1301.13,0,476685,...,2,YES,46200,4200,8400,33600,Dodge,Neon,2003,Y
15,473,58,892874,10/19/1992,IN,100/300,2000,1131.40,0,458733,...,0,NO,63120,10520,10520,42080,Accura,MDX,1999,Y
16,70,26,558938,6/8/2005,OH,500/1000,1000,1199.44,5000000,619884,...,2,YES,52110,5790,5790,40530,Nissan,Maxima,2012,N
17,140,31,275265,11/15/2004,IN,500/1000,500,708.64,6000000,470610,...,2,YES,77880,14160,7080,56640,Suburu,Legacy,2015,N
18,160,37,921202,12/28/2014,OH,500/1000,500,1374.22,0,472135,...,0,NO,72930,6630,13260,53040,Accura,TL,2015,N
19,196,39,143972,8/2/1992,IN,500/1000,2000,1475.73,0,477670,...,0,NO,60400,6040,6040,48320,Nissan,Pathfinder,2014,N
20,460,62,183430,6/25/2002,IN,250/500,1000,1187.96,4000000,618845,...,0,?,47160,0,5240,41920,Suburu,Impreza,2011,N
21,217,41,431876,11/27/2005,IL,500/1000,2000,875.15,0,442479,...,2,?,37840,0,4730,33110,Accura,RSX,1996,N
22,370,55,285496,5/27/1994,IL,100/300,2000,972.18,0,443920,...,0,YES,71520,17880,5960,47680,Suburu,Forrestor,2000,Y
23,413,55,115399,2/8/1991,IN,100/300,2000,1268.79,0,453148,...,2,?,98160,8180,16360,73620,Dodge,RAM,2011,Y
24,237,40,736882,2/2/1996,IN,100/300,1000,883.31,0,434733,...,3,NO,77880,7080,14160,56640,Ford,Escape,2005,N
25,8,35,699044,12/5/2013,OH,100/300,2000,1266.92,0,613982,...,3,YES,71500,16500,11000,44000,Ford,Escape,2006,Y
26,257,43,863236,9/20/1990,IN,100/300,2000,1322.10,0,436984,...,3,YES,9020,1640,820,6560,Toyota,Camry,2005,N
27,202,34,608513,7/18/2002,IN,100/300,500,848.07,3000000,607730,...,1,?,5720,1040,520,4160,Suburu,Forrestor,2003,Y
28,224,40,914088,2/8/1990,OH,100/300,2000,1291.70,0,609837,...,0,YES,69840,7760,15520,46560,Dodge,Neon,2009,N
29,241,45,596785,3/4/2014,IL,500/1000,2000,1104.50,0,432211,...,2,NO,91650,14100,14100,63450,Accura,TL,2011,N
30,64,25,908616,2/18/2000,IL,250/500,1000,954.16,0,473328,...,0,?,75600,12600,12600,50400,Toyota,Corolla,2005,N
31,166,37,666333,6/19/2008,IL,100/300,2000,1337.28,8000000,610393,...,2,?,67140,7460,7460,52220,Ford,F150,2006,Y
32,155,35,336614,8/1/2003,IL,500/1000,1000,1088.34,0,614780,...,3,NO,29790,3310,3310,23170,BMW,3 Series,2008,N
33,114,30,584859,4/4/1992,IL,100/300,1000,1558.29,0,472248,...,2,?,77110,14020,14020,49070,Suburu,Impreza,2015,N
34,149,37,990493,1/13/1991,IL,500/1000,500,1415.68,0,603381,...,1,YES,64800,10800,5400,48600,Audi,A3,1999,N
35,147,33,129872,8/8/2010,OH,100/300,1000,1334.15,6000000,479224,...,0,YES,53100,10620,5310,37170,Mercedes,C300,1995,Y
36,62,28,200152,3/9/2003,IL,100/300,1000,988.45,0,430141,...,1,YES,60200,6020,6020,48160,Suburu,Forrestor,2004,Y
37,289,49,933293,2/3/1993,IL,500/1000,2000,1222.48,0,620757,...,1,YES,5330,1230,820,3280,Suburu,Legacy,2001,N
38,431,54,485664,11/25/2002,IN,500/1000,2000,1155.55,0,615901,...,0,?,62300,12460,6230,43610,Jeep,Wrangler,2007,N
39,199,37,982871,7/27/1997,IN,250/500,500,1262.08,0,474615,...,3,NO,60170,10940,10940,38290,Nissan,Pathfinder,2011,Y
40,79,26,206213,5/8/1995,IL,100/300,500,1451.62,0,456446,...,2,?,40000,8000,4000,28000,BMW,M5,2010,N
41,116,34,616337,8/30/2012,IN,250/500,500,1737.66,0,470577,...,1,?,97080,16180,16180,64720,BMW,X5,2001,Y
42,37,23,448961,4/30/2006,IL,500/1000,500,1475.93,0,441648,...,0,NO,51660,5740,5740,40180,Dodge,RAM,2010,N
43,106,30,790442,4/13/2003,OH,250/500,500,538.17,0,433782,...,2,NO,51120,5680,5680,39760,Mercedes,E400,2005,N
44,269,44,108844,12/5/2007,IL,100/300,2000,1081.08,0,468104,...,2,?,56400,11280,11280,33840,Toyota,Highlander,2014,N
45,265,40,430029,8/21/2006,IL,250/500,1000,1454.43,0,459407,...,3,?,55120,6890,0,48230,Accura,MDX,2002,N
46,163,33,529112,1/8/1990,IN,100/300,500,1240.47,0,472573,...,1,?,77110,0,14020,63090,Honda,Civic,2014,N
47,355,47,939631,3/18/1990,OH,500/1000,2000,1273.70,4000000,433473,...,1,NO,62800,6280,6280,50240,Audi,A3,2003,Y
48,175,34,866931,1/7/2008,IN,500/1000,1000,1123.87,8000000,446326,...,0,YES,7290,810,810,5670,Volkswagen,Passat,1995,N
49,192,35,582011,3/10/1997,IL,100/300,1000,1245.89,0,435481,...,0,?,76600,15320,7660,53620,Mercedes,C300,2000,N

In [15]:
x.columns

Index(['months_as_customer', 'age', 'policy_number', 'policy_bind_date',
       'policy_state', 'policy_csl', 'policy_deductable',
       'policy_annual_premium', 'umbrella_limit', 'insured_zip', 'insured_sex',
       'insured_education_level', 'insured_occupation', 'insured_hobbies',
       'insured_relationship', 'capital-gains', 'capital-loss',
       'incident_date', 'incident_type', 'collision_type', 'incident_severity',
       'authorities_contacted', 'incident_state', 'incident_city',
       'incident_location', 'incident_hour_of_the_day',
       'number_of_vehicles_involved', 'property_damage', 'bodily_injuries',
       'witnesses', 'police_report_available', 'total_claim_amount',
       'injury_claim', 'property_claim', 'vehicle_claim', 'auto_make',
       'auto_model', 'auto_year', 'fraud_reported'],
      dtype='object')

In [16]:
pra = pd.read_csv("Police_report_available_imputed.csv")
ty = pra['police_report_available']
ty

0     YES
1      NO
2      NO
3      NO
4      NO
5      NO
6      NO
7     YES
8     YES
9      NO
10     NO
11    YES
12     NO
13     NO
14    YES
15     NO
16    YES
17    YES
18     NO
19     NO
20     NO
21     NO
22    YES
23     NO
24     NO
25    YES
26    YES
27     NO
28    YES
29     NO
30     NO
31     NO
32     NO
33     NO
34    YES
35    YES
36    YES
37    YES
38     NO
39     NO
40     NO
41     NO
42     NO
43     NO
44     NO
45     NO
46     NO
47     NO
48    YES
49     NO
Name: police_report_available, dtype: object

In [17]:
x['police_report_available']

0     YES
1       ?
2      NO
3      NO
4      NO
5      NO
6       ?
7     YES
8     YES
9       ?
10      ?
11    YES
12     NO
13     NO
14    YES
15     NO
16    YES
17    YES
18     NO
19     NO
20      ?
21      ?
22    YES
23      ?
24     NO
25    YES
26    YES
27      ?
28    YES
29     NO
30      ?
31      ?
32     NO
33      ?
34    YES
35    YES
36    YES
37    YES
38      ?
39     NO
40      ?
41      ?
42     NO
43     NO
44      ?
45      ?
46      ?
47     NO
48    YES
49      ?
Name: police_report_available, dtype: object

In [18]:
x['police_report_available'] = ty

In [19]:
x

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported
0,328,48,521585,10/17/2014,OH,250/500,1000,1406.91,0,466132,...,2,YES,71610,6510,13020,52080,Saab,92x,2004,Y
1,228,42,342868,6/27/2006,IN,250/500,2000,1197.22,5000000,468176,...,0,NO,5070,780,780,3510,Mercedes,E400,2007,Y
2,134,29,687698,9/6/2000,OH,100/300,2000,1413.14,5000000,430632,...,3,NO,34650,7700,3850,23100,Dodge,RAM,2007,N
3,256,41,227811,5/25/1990,IL,250/500,2000,1415.74,6000000,608117,...,2,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y
4,228,44,367455,6/6/2014,IL,500/1000,1000,1583.91,6000000,610706,...,1,NO,6500,1300,650,4550,Accura,RSX,2009,N
5,256,39,104594,10/12/2006,OH,250/500,1000,1351.10,0,478456,...,2,NO,64100,6410,6410,51280,Saab,95,2003,Y
6,137,34,413978,6/4/2000,IN,250/500,1000,1333.35,0,441716,...,0,NO,78650,21450,7150,50050,Nissan,Pathfinder,2012,N
7,165,37,429027,2/3/1990,IL,100/300,1000,1137.03,0,603195,...,2,YES,51590,9380,9380,32830,Audi,A5,2015,N
8,27,33,485665,2/5/1997,IL,100/300,500,1442.99,0,601734,...,1,YES,27700,2770,2770,22160,Toyota,Camry,2012,N
9,212,42,636550,7/25/2011,IL,100/300,500,1315.68,0,600983,...,1,NO,42300,4700,4700,32900,Saab,92x,1996,N
10,235,42,543610,5/26/2002,OH,100/300,500,1253.12,4000000,462283,...,2,NO,87010,7910,15820,63280,Ford,F150,2002,N
11,447,61,214618,5/29/1999,OH,100/300,2000,1137.16,0,615561,...,2,YES,114920,17680,17680,79560,Audi,A3,2006,N
12,60,23,842643,11/20/1997,OH,500/1000,500,1215.36,3000000,432220,...,0,NO,56520,4710,9420,42390,Saab,95,2000,N
13,121,34,626808,10/26/2012,OH,100/300,1000,936.61,0,464652,...,1,NO,7280,1120,1120,5040,Toyota,Highlander,2010,N
14,180,38,644081,12/28/1998,OH,250/500,2000,1301.13,0,476685,...,2,YES,46200,4200,8400,33600,Dodge,Neon,2003,Y
15,473,58,892874,10/19/1992,IN,100/300,2000,1131.40,0,458733,...,0,NO,63120,10520,10520,42080,Accura,MDX,1999,Y
16,70,26,558938,6/8/2005,OH,500/1000,1000,1199.44,5000000,619884,...,2,YES,52110,5790,5790,40530,Nissan,Maxima,2012,N
17,140,31,275265,11/15/2004,IN,500/1000,500,708.64,6000000,470610,...,2,YES,77880,14160,7080,56640,Suburu,Legacy,2015,N
18,160,37,921202,12/28/2014,OH,500/1000,500,1374.22,0,472135,...,0,NO,72930,6630,13260,53040,Accura,TL,2015,N
19,196,39,143972,8/2/1992,IN,500/1000,2000,1475.73,0,477670,...,0,NO,60400,6040,6040,48320,Nissan,Pathfinder,2014,N
20,460,62,183430,6/25/2002,IN,250/500,1000,1187.96,4000000,618845,...,0,NO,47160,0,5240,41920,Suburu,Impreza,2011,N
21,217,41,431876,11/27/2005,IL,500/1000,2000,875.15,0,442479,...,2,NO,37840,0,4730,33110,Accura,RSX,1996,N
22,370,55,285496,5/27/1994,IL,100/300,2000,972.18,0,443920,...,0,YES,71520,17880,5960,47680,Suburu,Forrestor,2000,Y
23,413,55,115399,2/8/1991,IN,100/300,2000,1268.79,0,453148,...,2,NO,98160,8180,16360,73620,Dodge,RAM,2011,Y
24,237,40,736882,2/2/1996,IN,100/300,1000,883.31,0,434733,...,3,NO,77880,7080,14160,56640,Ford,Escape,2005,N
25,8,35,699044,12/5/2013,OH,100/300,2000,1266.92,0,613982,...,3,YES,71500,16500,11000,44000,Ford,Escape,2006,Y
26,257,43,863236,9/20/1990,IN,100/300,2000,1322.10,0,436984,...,3,YES,9020,1640,820,6560,Toyota,Camry,2005,N
27,202,34,608513,7/18/2002,IN,100/300,500,848.07,3000000,607730,...,1,NO,5720,1040,520,4160,Suburu,Forrestor,2003,Y
28,224,40,914088,2/8/1990,OH,100/300,2000,1291.70,0,609837,...,0,YES,69840,7760,15520,46560,Dodge,Neon,2009,N
29,241,45,596785,3/4/2014,IL,500/1000,2000,1104.50,0,432211,...,2,NO,91650,14100,14100,63450,Accura,TL,2011,N
30,64,25,908616,2/18/2000,IL,250/500,1000,954.16,0,473328,...,0,NO,75600,12600,12600,50400,Toyota,Corolla,2005,N
31,166,37,666333,6/19/2008,IL,100/300,2000,1337.28,8000000,610393,...,2,NO,67140,7460,7460,52220,Ford,F150,2006,Y
32,155,35,336614,8/1/2003,IL,500/1000,1000,1088.34,0,614780,...,3,NO,29790,3310,3310,23170,BMW,3 Series,2008,N
33,114,30,584859,4/4/1992,IL,100/300,1000,1558.29,0,472248,...,2,NO,77110,14020,14020,49070,Suburu,Impreza,2015,N
34,149,37,990493,1/13/1991,IL,500/1000,500,1415.68,0,603381,...,1,YES,64800,10800,5400,48600,Audi,A3,1999,N
35,147,33,129872,8/8/2010,OH,100/300,1000,1334.15,6000000,479224,...,0,YES,53100,10620,5310,37170,Mercedes,C300,1995,Y
36,62,28,200152,3/9/2003,IL,100/300,1000,988.45,0,430141,...,1,YES,60200,6020,6020,48160,Suburu,Forrestor,2004,Y
37,289,49,933293,2/3/1993,IL,500/1000,2000,1222.48,0,620757,...,1,YES,5330,1230,820,3280,Suburu,Legacy,2001,N
38,431,54,485664,11/25/2002,IN,500/1000,2000,1155.55,0,615901,...,0,NO,62300,12460,6230,43610,Jeep,Wrangler,2007,N
39,199,37,982871,7/27/1997,IN,250/500,500,1262.08,0,474615,...,3,NO,60170,10940,10940,38290,Nissan,Pathfinder,2011,Y
40,79,26,206213,5/8/1995,IL,100/300,500,1451.62,0,456446,...,2,NO,40000,8000,4000,28000,BMW,M5,2010,N
41,116,34,616337,8/30/2012,IN,250/500,500,1737.66,0,470577,...,1,NO,97080,16180,16180,64720,BMW,X5,2001,Y
42,37,23,448961,4/30/2006,IL,500/1000,500,1475.93,0,441648,...,0,NO,51660,5740,5740,40180,Dodge,RAM,2010,N
43,106,30,790442,4/13/2003,OH,250/500,500,538.17,0,433782,...,2,NO,51120,5680,5680,39760,Mercedes,E400,2005,N
44,269,44,108844,12/5/2007,IL,100/300,2000,1081.08,0,468104,...,2,NO,56400,11280,11280,33840,Toyota,Highlander,2014,N
45,265,40,430029,8/21/2006,IL,250/500,1000,1454.43,0,459407,...,3,NO,55120,6890,0,48230,Accura,MDX,2002,N
46,163,33,529112,1/8/1990,IN,100/300,500,1240.47,0,472573,...,1,NO,77110,0,14020,63090,Honda,Civic,2014,N
47,355,47,939631,3/18/1990,OH,500/1000,2000,1273.70,4000000,433473,...,1,NO,62800,6280,6280,50240,Audi,A3,2003,Y
48,175,34,866931,1/7/2008,IN,500/1000,1000,1123.87,8000000,446326,...,0,YES,7290,810,810,5670,Volkswagen,Passat,1995,N
49,192,35,582011,3/10/1997,IL,100/300,1000,1245.89,0,435481,...,0,NO,76600,15320,7660,53620,Mercedes,C300,2000,N

In [20]:
x['police_report_available']

0     YES
1      NO
2      NO
3      NO
4      NO
5      NO
6      NO
7     YES
8     YES
9      NO
10     NO
11    YES
12     NO
13     NO
14    YES
15     NO
16    YES
17    YES
18     NO
19     NO
20     NO
21     NO
22    YES
23     NO
24     NO
25    YES
26    YES
27     NO
28    YES
29     NO
30     NO
31     NO
32     NO
33     NO
34    YES
35    YES
36    YES
37    YES
38     NO
39     NO
40     NO
41     NO
42     NO
43     NO
44     NO
45     NO
46     NO
47     NO
48    YES
49     NO
Name: police_report_available, dtype: object

# This above like how we can make a class for model training wrt filling missing values but this is just a sample and we won't be compleltely implementing this bcoz of time constraint

# TO make a complete class wrt model training, we need to combine codes of trial_file.ipynb and this current file.